// app/demo/page.tsx
import { buildPlanFromAnswers, type Answers } from "@/lib/planBuilder";
import { PlanClient } from "@/app/plan/[id]/plan-client";

export default function DemoPage() {
  // Hard-coded example answers for the demo
  const demoAnswers: Answers = {
    goal: "muscle_gain",
    daysPerWeek: 4,
    equipment: "gym",
    timeOfDay: "evening",
    experience: "intermediate",
    wantNutrition: false,
  };

  const plan = buildPlanFromAnswers(demoAnswers);

  return (
    <main className="min-h-screen bg-gradient-to-b from-background via-background to-muted/40">
      <div className="max-w-4xl mx-auto px-4 py-10 space-y-8">
        <header className="space-y-2">
          <h1 className="text-2xl font-semibold tracking-tight">
            Demo: 4-day Upper / Lower routine
          </h1>
          <p className="text-sm text-muted-foreground max-w-xl">
            This is an example week generated by routinelab for someone training 4 days per week
            in a gym with a muscle-gain goal. Check things off, add notes, and see how the
            tracker feels. To build your own,{" "}
            <a href="/start" className="underline underline-offset-2">
              start here
            </a>.
          </p>
        </header>

        {/* Reuse the same client tracker with a fixed demo id */}
        <PlanClient id="demo-upper-lower" plan={plan} />
      </div>
    </main>
  );
}
